/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package HM_UI;

import HM_Model.CommunityDirectory;
import HM_Model.Doctor;
import HM_Model.DoctorDirectory;
import HM_Model.Encounter;
import HM_Model.EncounterDetails;
import HM_Model.HospitalDirectory;
import HM_Model.Patient;
import HM_Model.PatientHistory;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adity
 */
public class H_AdminEncounter extends javax.swing.JPanel {

    /**
     * Creates new form H_AdminEncounter
     */
     HospitalDirectory hospitalDirectory;
   CommunityDirectory communityDirectory;
   JSplitPane sp;
   PatientHistory patientHistory;
   DoctorDirectory doctorDirectory;
      EncounterDetails encounterDetails;
    
    
    public H_AdminEncounter(DoctorDirectory doctorDirectory, PatientHistory patientHistory, EncounterDetails encounterDetails) {
        initComponents();
        this.hospitalDirectory=hospitalDirectory;
        this.patientHistory=patientHistory;
        this.doctorDirectory=doctorDirectory;
        this.sp=sp;
        this.encounterDetails=encounterDetails;
                
        populateDocTable();
        populatePatientTable();
        populateEncounterTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tblPatientView = new javax.swing.JTable();
        lblDoctor = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDoctorView = new javax.swing.JTable();
        lblPatient = new javax.swing.JLabel();
        calenderSlot = new com.toedter.calendar.JDateChooser();
        lblSelectDate = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaPatientProblem = new javax.swing.JTextArea();
        lblPatientProblem = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblEncounterView = new javax.swing.JTable();
        lblEncounter = new javax.swing.JLabel();
        btnBook = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        tblPatientView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "Patient Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblPatientView);

        add(jScrollPane3);
        jScrollPane3.setBounds(185, 308, 710, 241);

        lblDoctor.setText("Doctors");
        add(lblDoctor);
        lblDoctor.setBounds(77, 119, 41, 16);

        tblDoctorView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor Name", "Speciality", "Hospital Name", "Hospital Location"
            }
        ));
        jScrollPane4.setViewportView(tblDoctorView);

        add(jScrollPane4);
        jScrollPane4.setBounds(185, 49, 710, 241);

        lblPatient.setText("Patients");
        add(lblPatient);
        lblPatient.setBounds(78, 383, 42, 16);
        add(calenderSlot);
        calenderSlot.setBounds(190, 849, 151, 22);

        lblSelectDate.setText("Select Date :");
        add(lblSelectDate);
        lblSelectDate.setBounds(74, 855, 70, 16);

        txtAreaPatientProblem.setColumns(20);
        txtAreaPatientProblem.setRows(5);
        jScrollPane2.setViewportView(txtAreaPatientProblem);

        add(jScrollPane2);
        jScrollPane2.setBounds(563, 814, 234, 86);

        lblPatientProblem.setText("Brief your Problem :");
        add(lblPatientProblem);
        lblPatientProblem.setBounds(446, 849, 105, 16);

        tblEncounterView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "Doctor Name", "Slot Details", "Patient Problem"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblEncounterView);

        add(jScrollPane5);
        jScrollPane5.setBounds(185, 567, 710, 241);

        lblEncounter.setText("Encounter");
        add(lblEncounter);
        lblEncounter.setBounds(74, 645, 54, 16);

        btnBook.setText("Create Encounter");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });
        add(btnBook);
        btnBook.setBounds(881, 845, 121, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\adity\\Downloads\\encounter_1410x1130.png")); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 1440, 1130);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Hospital Admin's Encounter View");
        add(jLabel1);
        jLabel1.setBounds(247, 10, 630, 30);
    }// </editor-fold>//GEN-END:initComponents

    
     private Patient getPatientByName(String name){
     for(Patient p : patientHistory.getPatientHistory()){
         if(p.getName().equals(name))
             return p;
     } 
     return null;
    }
    private Doctor getDoctorByName(String name){
     for(Doctor d : doctorDirectory.getDoctorDirectory()){
         if(d.getName().equals(name))
             return d;
     }
        return null;   
    }
    
     private Encounter getEncounterByPandD(String p,String d){
     for(Encounter e : encounterDetails.getEncounterDetails()){   
      if(e.getP().getName().equals(p) && e.getD().getName().equals(d))
          return e;
     }
     return null;
    }
     
           private void populateDocTable() {
        DefaultTableModel model = (DefaultTableModel) tblDoctorView.getModel();
        model.setRowCount(0);
        for(Doctor d:doctorDirectory.getDoctorDirectory()){
            Object[] rows = new Object[4];
            rows[0]= d;
            rows[1]=d.getSpeciality();
            rows[2]=d.getHospitalName();
            rows[3]=d.getHospitalLocation();
            
            model.addRow(rows);
    }
    }
       
     private void populatePatientTable(){
        DefaultTableModel model =(DefaultTableModel) tblPatientView.getModel();
        model.setRowCount(0);
        for(Patient p : patientHistory.getPatientHistory()){
            Object[] rows = new Object[2];
            rows[0]=p;
            rows[1]=p.getEmail();
            
            model.addRow(rows);
        }
    }
     
    private void populateEncounterTable(){
     DefaultTableModel model =(DefaultTableModel) tblEncounterView.getModel();
     model.setRowCount(0);   
        for(Encounter e : encounterDetails.getEncounterDetails()){
            Object[] rows = new Object[4];
            rows[0]=e.getP();
            rows[1]=e.getD();
            rows[2]=e.getEncDate();
            rows[3]=e.getPatientProblem();
            
            model.addRow(rows);
    }
    }
    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model1 = (DefaultTableModel) tblDoctorView.getModel();
        DefaultTableModel model2 = (DefaultTableModel) tblPatientView.getModel();

        int index1 = tblDoctorView.getSelectedRow();
        int index2 = tblPatientView.getSelectedRow();
         if(index1<0){
            JOptionPane.showMessageDialog(this,"Please Select your Doctor");
            return;
        } 
        if(index2<0){
            JOptionPane.showMessageDialog(this,"Please Select your Patient");
            return;
        }
        SimpleDateFormat df= new SimpleDateFormat("MM-dd-yyyy") {};
        String date = df.format(calenderSlot.getDate().getTime());

        Encounter e = encounterDetails.addEncounter();
        e.setD(getDoctorByName(String.valueOf(model1.getValueAt(index1, 0))));
        e.setP(getPatientByName(String.valueOf(model2.getValueAt(index2, 0))));
        e.setEncDate(date);
        e.setPatientProblem(txtAreaPatientProblem.getText());

        JOptionPane.showMessageDialog(this,"Encounter Booked...");

        populateEncounterTable();
    }//GEN-LAST:event_btnBookActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private com.toedter.calendar.JDateChooser calenderSlot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblDoctor;
    private javax.swing.JLabel lblEncounter;
    private javax.swing.JLabel lblPatient;
    private javax.swing.JLabel lblPatientProblem;
    private javax.swing.JLabel lblSelectDate;
    private javax.swing.JTable tblDoctorView;
    private javax.swing.JTable tblEncounterView;
    private javax.swing.JTable tblPatientView;
    private javax.swing.JTextArea txtAreaPatientProblem;
    // End of variables declaration//GEN-END:variables
}
