/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package HM_UI;

import HM_Model.CommunityDirectory;
import HM_Model.DoctorDirectory;
import HM_Model.EncounterDetails;
import HM_Model.HospitalDirectory;
import HM_Model.HouseDirectory;
import HM_Model.PatientHistory;
import javax.swing.JSplitPane;

/**
 *
 * @author adity
 */
public class HospitalAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalAdminPanel
     */
    JSplitPane sp;
    PatientHistory patientHistory;
    DoctorDirectory doctorDirectory;
    HospitalDirectory hospitalDirectory;
    EncounterDetails encounterDetails;
    CommunityDirectory communityDirectory;
    
    public HospitalAdminPanel(EncounterDetails encounterDetails, JSplitPane sp, PatientHistory patientHistory, HospitalDirectory hospitalDirectory, DoctorDirectory doctorDirectory, CommunityDirectory communityDirectory) {
        initComponents();
        this.patientHistory=patientHistory;
        this.sp=sp;
        this.doctorDirectory=doctorDirectory;
        this.communityDirectory=communityDirectory;
        this.hospitalDirectory=hospitalDirectory;
        this.encounterDetails=encounterDetails;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDoctor = new javax.swing.JButton();
        btnPatient = new javax.swing.JButton();
        btnHospitals = new javax.swing.JButton();
        btnEncounter = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        btnDoctor.setBackground(new java.awt.Color(0, 0, 0));
        btnDoctor.setForeground(new java.awt.Color(255, 255, 255));
        btnDoctor.setText("Doctor");
        btnDoctor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorActionPerformed(evt);
            }
        });
        add(btnDoctor);
        btnDoctor.setBounds(40, 270, 110, 40);

        btnPatient.setBackground(new java.awt.Color(0, 0, 0));
        btnPatient.setForeground(new java.awt.Color(255, 255, 255));
        btnPatient.setText("Patient");
        btnPatient.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientActionPerformed(evt);
            }
        });
        add(btnPatient);
        btnPatient.setBounds(37, 196, 110, 40);

        btnHospitals.setBackground(new java.awt.Color(0, 0, 0));
        btnHospitals.setForeground(new java.awt.Color(255, 255, 255));
        btnHospitals.setText("Hospital");
        btnHospitals.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHospitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospitalsActionPerformed(evt);
            }
        });
        add(btnHospitals);
        btnHospitals.setBounds(40, 340, 110, 40);

        btnEncounter.setBackground(new java.awt.Color(0, 0, 0));
        btnEncounter.setForeground(new java.awt.Color(255, 255, 255));
        btnEncounter.setText("Encounter");
        btnEncounter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncounterActionPerformed(evt);
            }
        });
        add(btnEncounter);
        btnEncounter.setBounds(40, 410, 110, 40);

        btnSignUp.setBackground(new java.awt.Color(0, 0, 0));
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("Create");
        btnSignUp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        add(btnSignUp);
        btnSignUp.setBounds(30, 710, 130, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\adity\\Downloads\\hospital-admin_1410x1130.jpeg")); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1410, 1130);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientActionPerformed
        // TODO add your handling code here:
        H_AdminPatientPanel happ= new H_AdminPatientPanel(patientHistory);
        sp.setRightComponent(happ);
    }//GEN-LAST:event_btnPatientActionPerformed

    private void btnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorActionPerformed
        // TODO add your handling code here:
        H_AdminDoctorPanel hadp=new H_AdminDoctorPanel(doctorDirectory);
        sp.setRightComponent(hadp);
    }//GEN-LAST:event_btnDoctorActionPerformed

    private void btnHospitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospitalsActionPerformed
        // TODO add your handling code here:
        H_AdminHospitalPanel hahp = new H_AdminHospitalPanel(communityDirectory,patientHistory,doctorDirectory,sp,hospitalDirectory);
        sp.setRightComponent(hahp);

    }//GEN-LAST:event_btnHospitalsActionPerformed

    private void btnEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncounterActionPerformed
        // TODO add your handling code here:
        H_AdminEncounter hae = new H_AdminEncounter(doctorDirectory,patientHistory, encounterDetails);
        sp.setRightComponent(hae);
    }//GEN-LAST:event_btnEncounterActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        H_AdminCreatePanel hacp = new H_AdminCreatePanel(patientHistory,doctorDirectory);
        sp.setRightComponent(hacp);
    }//GEN-LAST:event_btnSignUpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoctor;
    private javax.swing.JButton btnEncounter;
    private javax.swing.JButton btnHospitals;
    private javax.swing.JButton btnPatient;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
