/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package HM_UI;

import HM_Model.CommunityAdmin;
import HM_Model.CommunityDirectory;
import HM_Model.Doctor;
import HM_Model.DoctorDirectory;
import HM_Model.EncounterDetails;
import HM_Model.HospitalAdmin;
import HM_Model.HospitalDirectory;
import HM_Model.HouseDirectory;
import HM_Model.Patient;
import HM_Model.PatientHistory;
import HM_Model.SystemAdmin;
import HM_Model.VitalSignsDirectory;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;

/**
 *
 * @author adity
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    JSplitPane sp;
    PatientHistory patientHistory;
    DoctorDirectory doctorDirectory;
    EncounterDetails encounterDetails;
    VitalSignsDirectory vitalSignsDirectory;
    SystemAdminPanel sa;
    SystemAdmin s;
    CommunityDirectory communityDirectory;
    HospitalDirectory hospitalDirectory;
    HouseDirectory houseDirectory;
    HospitalAdmin h;
    CommunityAdmin c;
    
    public LoginPanel( HospitalAdmin h,SystemAdmin s,PatientHistory patientHistory, DoctorDirectory doctorDirectory, JSplitPane sp, EncounterDetails encounterDetails, VitalSignsDirectory vitalSignsDirectory, CommunityDirectory communityDirectory, HospitalDirectory hospitalDirectory) {
        initComponents();
        this.patientHistory= patientHistory;
        this.doctorDirectory=doctorDirectory;
        this.sp=sp;
        this.s=new SystemAdmin();
        this.h=new HospitalAdmin();
        this.c=new CommunityAdmin();
        this.encounterDetails=encounterDetails;
        this.vitalSignsDirectory=vitalSignsDirectory;
        this.communityDirectory=communityDirectory;
        this.hospitalDirectory=hospitalDirectory;
        
        lblEmail.setVisible(false);
        lblPassword.setVisible(false);
        lblCategory.setVisible(false);
        txtPassword1.setVisible(false);
    }
       
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeading1 = new javax.swing.JLabel();
        lblHeading2 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtPassword1 = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        lblCategory = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1000, 1000));
        setLayout(null);

        lblHeading1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        lblHeading1.setForeground(new java.awt.Color(255, 255, 255));
        lblHeading1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading1.setText("Boston Hospital");
        add(lblHeading1);
        lblHeading1.setBounds(16, 33, 685, 62);

        lblHeading2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblHeading2.setForeground(new java.awt.Color(255, 255, 255));
        lblHeading2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading2.setText("Please Login into your Account..!!");
        add(lblHeading2);
        lblHeading2.setBounds(133, 138, 470, 40);

        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email :");
        add(lblEmail);
        lblEmail.setBounds(112, 251, 50, 16);

        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password :");
        add(lblPassword);
        lblPassword.setBounds(90, 299, 70, 16);

        txtPassword1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        add(txtPassword1);
        txtPassword1.setBounds(190, 770, 360, 60);

        btnLogin.setText("Login");
        btnLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(255, 255, 255)));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        add(btnLogin);
        btnLogin.setBounds(240, 560, 100, 50);

        lblCategory.setForeground(new java.awt.Color(255, 255, 255));
        lblCategory.setText("Category :");
        add(lblCategory);
        lblCategory.setBounds(98, 365, 60, 16);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "** Select your Category **", "Doctor", "Patient", "System Admin", "Hospital Admin", "Community Admin" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Category", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N
        add(jComboBox1);
        jComboBox1.setBounds(180, 440, 200, 60);

        txtEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email ID", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        add(txtEmail);
        txtEmail.setBounds(180, 250, 360, 60);

        txtPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        add(txtPassword);
        txtPassword.setBounds(180, 340, 360, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\adity\\Downloads\\Login 1410x1130.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1260, 1000);
    }// </editor-fold>//GEN-END:initComponents
    
    String email;
    String password;
    String role;
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        
        //DoctorPanel dp = new DoctorPanel(doctorDirectory, patientHistory, d, encounterDetails);
            try{
                email = txtEmail.getText();
                password = String.valueOf(txtPassword.getPassword());
                role=jComboBox1.getSelectedItem().toString();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(this, "Please enter correct values..!!");
            }
            
            
            /*if(email.equals("test123") && password.equals("password")){
            JOptionPane.showMessageDialog(this, "Login Successful..!!");}
            else{JOptionPane.showMessageDialog(this, "Please Enter Valid Credentials..!!");}
            */
            if(checkfield()){
                if(role.equals("Patient"))  {  
                    if(patientHistory.getSearch(email, password)){
                        JOptionPane.showMessageDialog(this, "Patient Login Successful..!!"); 
                        Patient p = patientHistory.getPatient(email, password);
                        PatientPanel pp= new PatientPanel(doctorDirectory,patientHistory,p,encounterDetails,vitalSignsDirectory);
                       
                        sp.setRightComponent(pp);
                        }
                    else{JOptionPane.showMessageDialog(this, "Please Enter Valid Credentials..!!");}
                }
            
                else if(role.equals("Doctor")){
                    if(doctorDirectory.getSearch(email, password)){
                        JOptionPane.showMessageDialog(this, "Doctor Login Successful..!!"); 
                        Doctor d=doctorDirectory.getDoctor(email,password);
                        DoctorPanel dp = new DoctorPanel(doctorDirectory, patientHistory,d,encounterDetails,vitalSignsDirectory);
                        sp.setRightComponent(dp);
                    }
                    else{JOptionPane.showMessageDialog(this, "Please Enter Valid Credentials..!!");}
                }
                else if(role.equals("System Admin")){
                    if(s.getEmailID().equalsIgnoreCase(email)&& s.getPassword().equals(password)){
                    JOptionPane.showMessageDialog(this, "System Admin Login Successful..!!"); 
                    SystemAdminPanel sap= new SystemAdminPanel(encounterDetails,sp, patientHistory,hospitalDirectory,doctorDirectory,communityDirectory);
                    sp.setRightComponent(sap);
                    }
                    else {JOptionPane.showMessageDialog(this, "Please Enter Valid Credentials..!!");}
                }
                else if(role.equals("Hospital Admin")){
                   if(h.getEmail().equalsIgnoreCase(email)&& h.getPassword().equals(password)){
                    JOptionPane.showMessageDialog(this, "Hospital Admin Login Successful..!!"); 
                    HospitalAdminPanel hap= new HospitalAdminPanel(encounterDetails, sp, patientHistory,hospitalDirectory,doctorDirectory,communityDirectory);
                    sp.setRightComponent(hap);
                    }
                    else {JOptionPane.showMessageDialog(this, "Please Enter Valid Credentials..!!");}   
                }
                else if(role.equals("Community Admin")){
                    if(c.getEmail().equalsIgnoreCase(email) && c.getPassword().equals("password"))
                    {JOptionPane.showMessageDialog(this, "Community Admin Login Successful..!!");
                      CommunityAdminPanel cap = new CommunityAdminPanel(encounterDetails, sp, patientHistory,hospitalDirectory,doctorDirectory,communityDirectory);
                      sp.setRightComponent(cap);
                    }
                    else{JOptionPane.showMessageDialog(this, "Please Enter Valid Credentials..!!");}
                        
                }
                else {JOptionPane.showMessageDialog(this, "Please Enter Valid Credentials..!!");}
            }
    }//GEN-LAST:event_btnLoginActionPerformed

    private boolean checkfield(){
    ArrayList msg=null;
    msg=new ArrayList();
    
    if(email.isBlank())
        msg.add(("Please enter the correct email (xxx@xx.com)"));
    if(password.isBlank())
        msg.add("Password field is empty");
    if(role.equals("** Select your Category **"))
        msg.add("Please Select A Category");
    
    if(!(msg.isEmpty()))
        {JOptionPane.showMessageDialog(this, msg.toArray());
        msg.clear();
        return false;}
        else 
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblHeading1;
    private javax.swing.JLabel lblHeading2;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPassword1;
    // End of variables declaration//GEN-END:variables

}