/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package HM_UI;

import HM_Model.CommunityDirectory;
import HM_Model.Doctor;
import HM_Model.DoctorDirectory;
import HM_Model.EncounterDetails;
import HM_Model.HospitalDirectory;
import HM_Model.HouseDirectory;
import HM_Model.PatientHistory;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adity
 */
public class SysAdminDoctorPanel extends javax.swing.JPanel {

    /**
     * Creates new form SysAdminDoctorPanel
     */
    DoctorDirectory doctorDirectory;
    Doctor d;
    HospitalDirectory hospitalDirectory;
   CommunityDirectory communityDirectory;
   JSplitPane sp;
   PatientHistory patientHistory;
   EncounterDetails encounterDetails;
    
    public SysAdminDoctorPanel(HouseDirectory houseDirectory, EncounterDetails encounterDetails, CommunityDirectory communityDirectory, PatientHistory patientHistory, DoctorDirectory doctorDirectory, JSplitPane sp, HospitalDirectory hospitalDirectory) {
        initComponents();
        this.doctorDirectory=doctorDirectory;
        this.d=d;
        this.hospitalDirectory=hospitalDirectory;
        this.communityDirectory=communityDirectory;
        this.patientHistory=patientHistory;
        this.doctorDirectory=doctorDirectory;
        this.sp=sp;
        this.encounterDetails=encounterDetails;

        populateDocTable();
        btnViewDetails.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnViewAll = new javax.swing.JButton();
        lblHeading2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDoctorView = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnViewDetails = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSpeciality = new javax.swing.JLabel();
        lblHospitalName = new javax.swing.JLabel();
        lblHospitalLocation = new javax.swing.JLabel();
        lblExperience = new javax.swing.JLabel();
        txtDName = new javax.swing.JTextField();
        txtDAge = new javax.swing.JTextField();
        txtDEmail = new javax.swing.JTextField();
        txtSpeciality = new javax.swing.JTextField();
        txtHospitalName = new javax.swing.JTextField();
        txtHospitalLocation = new javax.swing.JTextField();
        txtExperience = new javax.swing.JTextField();
        lblDPhone = new javax.swing.JLabel();
        txtDPhone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);
        add(txtSearch);
        txtSearch.setBounds(290, 70, 218, 22);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch);
        btnSearch.setBounds(210, 70, 72, 23);

        btnViewAll.setText("View All");
        btnViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllActionPerformed(evt);
            }
        });
        add(btnViewAll);
        btnViewAll.setBounds(790, 70, 72, 23);

        lblHeading2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lblHeading2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading2.setText("System Admin's Doctors View");
        add(lblHeading2);
        lblHeading2.setBounds(250, 20, 540, 29);

        tblDoctorView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor Name", "Speciality", "Hospital Name", "Hospital Location"
            }
        ));
        tblDoctorView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDoctorViewMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblDoctorView);

        add(jScrollPane3);
        jScrollPane3.setBounds(210, 120, 710, 241);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate);
        btnUpdate.setBounds(350, 370, 72, 23);

        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });
        add(btnViewDetails);
        btnViewDetails.setBounds(210, 370, 93, 23);

        btnDelete.setText("Delete ");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete);
        btnDelete.setBounds(680, 370, 72, 23);

        lblName.setText("Doctor Name :");
        add(lblName);
        lblName.setBounds(400, 420, 90, 16);

        lblAge.setText("Age :");
        add(lblAge);
        lblAge.setBounds(440, 460, 40, 16);

        lblEmail.setText("Email :");
        add(lblEmail);
        lblEmail.setBounds(430, 500, 60, 16);

        lblSpeciality.setText("Speciality :");
        add(lblSpeciality);
        lblSpeciality.setBounds(420, 540, 70, 16);

        lblHospitalName.setText("Hospital Name :");
        add(lblHospitalName);
        lblHospitalName.setBounds(390, 580, 100, 16);

        lblHospitalLocation.setText("Hospital Location :");
        add(lblHospitalLocation);
        lblHospitalLocation.setBounds(380, 620, 120, 16);

        lblExperience.setText("Experience :");
        add(lblExperience);
        lblExperience.setBounds(400, 660, 90, 16);
        add(txtDName);
        txtDName.setBounds(510, 420, 180, 30);
        add(txtDAge);
        txtDAge.setBounds(510, 460, 180, 30);
        add(txtDEmail);
        txtDEmail.setBounds(510, 500, 180, 30);
        add(txtSpeciality);
        txtSpeciality.setBounds(510, 540, 180, 30);
        add(txtHospitalName);
        txtHospitalName.setBounds(510, 580, 180, 30);
        add(txtHospitalLocation);
        txtHospitalLocation.setBounds(510, 620, 180, 30);
        add(txtExperience);
        txtExperience.setBounds(510, 660, 180, 30);

        lblDPhone.setText("Phone");
        add(lblDPhone);
        lblDPhone.setBounds(420, 700, 70, 16);
        add(txtDPhone);
        txtDPhone.setBounds(510, 700, 180, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\adity\\Downloads\\doctor-netherlands-1920x1080_1410x1130.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1451, 1130);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String search=txtSearch.getText();
        var result = doctorDirectory.doctorSearch(search);
        populateDocSearch(result);
        txtSearch.setText("");
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllActionPerformed
        // TODO add your handling code here:
        populateDocTable();
        txtSearch.setText("");
    }//GEN-LAST:event_btnViewAllActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
         int selectedRowIndex = tblDoctorView.getSelectedRow();
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this,"Please Select the Patient to Update their Details");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblDoctorView.getModel();
        Doctor selecteddoctor=(Doctor) model.getValueAt(selectedRowIndex, 0);
        
        try{
            if(checkfield()){
                selecteddoctor.setName(txtDName.getText());
                selecteddoctor.setdAge(Integer.parseInt(txtDAge.getText()));
                selecteddoctor.setEmail(txtDEmail.getText());
                selecteddoctor.setSpeciality(txtSpeciality.getText());
                selecteddoctor.setExperience(Double.parseDouble(txtExperience.getText()));
                selecteddoctor.setHospitalName(txtHospitalName.getText());
                selecteddoctor.setHospitalLocation(txtHospitalLocation.getText());
                selecteddoctor.setPhone(Long.parseLong(txtDPhone.getText()));
                
                JOptionPane.showMessageDialog(this, "Your Details Have Been Updated..!!");
                populateDocTable();
                
                txtDName.setText("");
                txtDAge.setText("");
                txtDEmail.setText("");
                txtSpeciality.setText("");
                txtExperience.setText("");
                txtHospitalName.setText("");
                txtHospitalLocation.setText("");
                txtDPhone.setText("");
            }
        }
        catch(Exception e){JOptionPane.showMessageDialog(this, "Please update with correct values..!!");}
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
        /* int selectedRowIndex = tblDoctorView.getSelectedRow();
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this,"Please Select the Patient to View their Details");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblDoctorView.getModel();
        Doctor selecteddoctor=(Doctor) model.getValueAt(selectedRowIndex, 0);
        
        txtDName.setText(selecteddoctor.getName());
        txtDAge.setText(String.valueOf(selecteddoctor.getdAge()));
        txtDEmail.setText(selecteddoctor.getEmail());
        txtSpeciality.setText(selecteddoctor.getSpeciality());
        txtExperience.setText(String.valueOf(selecteddoctor.getExperience()));
        txtHospitalName.setText(selecteddoctor.getHospitalName());
        txtHospitalLocation.setText(selecteddoctor.getHospitalLocation());
        txtDPhone.setText(String.valueOf(selecteddoctor.getPhone()));*/
        
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
          int selectedRowIndex = tblDoctorView.getSelectedRow();

        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this,"Please Select a Doctor to Delete");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblDoctorView.getModel();
        Doctor selectedDoctor=(Doctor) model.getValueAt(selectedRowIndex, 0);
        
        doctorDirectory.deleteDoctor(selectedDoctor);
        JOptionPane.showMessageDialog(this,"Doctor Deleted");
        populateDocTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblDoctorViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDoctorViewMouseClicked
        // TODO add your handling code here:
       int selectedRowIndex = tblDoctorView.getSelectedRow();
        if(selectedRowIndex<0){
            JOptionPane.showMessageDialog(this,"Please Select the Patient to View their Details");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) tblDoctorView.getModel();
        Doctor selecteddoctor=(Doctor) model.getValueAt(selectedRowIndex, 0);
        
        txtDName.setText(selecteddoctor.getName());
        txtDAge.setText(String.valueOf(selecteddoctor.getdAge()));
        txtDEmail.setText(selecteddoctor.getEmail());
        txtSpeciality.setText(selecteddoctor.getSpeciality());
        txtExperience.setText(String.valueOf(selecteddoctor.getExperience()));
        txtHospitalName.setText(selecteddoctor.getHospitalName());
        txtHospitalLocation.setText(selecteddoctor.getHospitalLocation());
        txtDPhone.setText(String.valueOf(selecteddoctor.getPhone()));   
    }//GEN-LAST:event_tblDoctorViewMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnViewAll;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblDPhone;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblExperience;
    private javax.swing.JLabel lblHeading2;
    private javax.swing.JLabel lblHospitalLocation;
    private javax.swing.JLabel lblHospitalName;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSpeciality;
    private javax.swing.JTable tblDoctorView;
    private javax.swing.JTextField txtDAge;
    private javax.swing.JTextField txtDEmail;
    private javax.swing.JTextField txtDName;
    private javax.swing.JTextField txtDPhone;
    private javax.swing.JTextField txtExperience;
    private javax.swing.JTextField txtHospitalLocation;
    private javax.swing.JTextField txtHospitalName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSpeciality;
    // End of variables declaration//GEN-END:variables

  private void populateDocTable() {
        DefaultTableModel model = (DefaultTableModel) tblDoctorView.getModel();
        model.setRowCount(0);
        for(Doctor d:doctorDirectory.getDoctorDirectory()){
            Object[] rows = new Object[4];
            rows[0]= d;
            rows[1]=d.getSpeciality();
            rows[2]=d.getHospitalName();
            rows[3]=d.getHospitalLocation();
            
            model.addRow(rows);
    }
    }
    
    private void populateDocSearch(ArrayList<Doctor> result) {
        DefaultTableModel model = (DefaultTableModel) tblDoctorView.getModel();
        model.setRowCount(0);
        for(Doctor d:result){
            Object[] rows = new Object[4];
            rows[0]= d;
            rows[1]=d.getSpeciality();
            rows[2]=d.getHospitalName();
            rows[3]=d.getHospitalLocation();
            
            model.addRow(rows);
        }
    }
    
    private boolean checkfield(){
    ArrayList msg=null;
    msg= new ArrayList();
    
     if(txtDName.getText().isBlank()|| !(txtDName.getText().matches("^[a-zA-Z ]*$")))
        {msg.add("Please enter the name without digits or special characters but do not leave it blank");}
     if(txtDEmail.getText().isBlank()||!(txtDEmail.getText().matches("^[A-Za-z0-9+_.-]+@(.+)$")))
        msg.add(("Please enter the correct email (xxx@xx.com)"));
     if(!(String.valueOf(txtDPhone.getText()).matches("^[0-9]{10}$")))
       {msg.add("Please enter the 10 digit mobile number");}
     if(Integer.parseInt(txtDAge.getText())<1 || Integer.parseInt(txtDAge.getText())>100)
             msg.add("Please enter the correct age between 1 and 100");
     if(txtSpeciality.getText().isBlank()|| !(txtSpeciality.getText().matches("^[a-zA-Z ]*$")))
             msg.add("Please enter the Speciality without digits or special characters but do not leave it blank");
     if(Double.parseDouble(txtExperience.getText())<0 || Double.parseDouble(txtExperience.getText())>75)
             msg.add("Please enter your correct experience");
     if(txtHospitalName.getText().isBlank()|| !(txtHospitalName.getText().matches("^[a-zA-Z ]*$")))
             msg.add("Please enter the Hospital name without special characters but do not leave it blank");
     if(txtHospitalLocation.getText().isBlank()|| !(txtHospitalLocation.getText().matches("^[a-zA-Z ]*$")))
             msg.add("Please enter the correct location without special characters but do not leave it blank");
 
     if(!(msg.isEmpty()))
        {JOptionPane.showMessageDialog(this, msg.toArray());
        msg.clear();
        return false;}
        else 
        return true;
    }
 }
    
