/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package HM_UI;

import HM_Model.Doctor;
import HM_Model.DoctorDirectory;
import HM_Model.Patient;
import HM_Model.PatientHistory;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author adity
 */
public class SysAdminCreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form SysAdminCreate
     */
    PatientHistory patientHistory;
    DoctorDirectory doctorDirectory;
    
    public SysAdminCreatePanel(PatientHistory patientHistory, DoctorDirectory doctorDirectory) {
        initComponents();
        this.patientHistory=patientHistory;
        this.doctorDirectory=doctorDirectory;
        Test();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtExperience = new javax.swing.JTextField();
        lblPAge = new javax.swing.JLabel();
        lblHeight = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        txtPAge = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        lblHospitalName = new javax.swing.JLabel();
        lblHospitalLocation = new javax.swing.JLabel();
        txtHospitalName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtHospitalLocation = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        cbGender = new javax.swing.JComboBox<>();
        lblRole = new javax.swing.JLabel();
        cbRole = new javax.swing.JComboBox<>();
        btnSignUP = new javax.swing.JButton();
        lblDAge = new javax.swing.JLabel();
        lblSpeciality = new javax.swing.JLabel();
        lblExperience = new javax.swing.JLabel();
        lblHeading1 = new javax.swing.JLabel();
        lblHeading2 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtDAge = new javax.swing.JTextField();
        txtSpeciality = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1410, 1130));
        setLayout(null);
        add(txtExperience);
        txtExperience.setBounds(327, 596, 112, 22);

        lblPAge.setText("Age :");
        add(lblPAge);
        lblPAge.setBounds(563, 509, 27, 16);

        lblHeight.setText("Height (in cms) :");
        add(lblHeight);
        lblHeight.setBounds(505, 559, 88, 16);

        lblWeight.setText("Weight (in lbs) :");
        add(lblWeight);
        lblWeight.setBounds(505, 599, 83, 16);
        add(txtPAge);
        txtPAge.setBounds(617, 509, 121, 22);
        add(txtHeight);
        txtHeight.setBounds(617, 556, 121, 22);
        add(txtWeight);
        txtWeight.setBounds(617, 596, 121, 22);

        lblHospitalName.setText("Hospital Name :");
        add(lblHospitalName);
        lblHospitalName.setBounds(210, 636, 85, 16);

        lblHospitalLocation.setText("Hospital Location :");
        add(lblHospitalLocation);
        lblHospitalLocation.setBounds(197, 676, 99, 16);
        add(txtHospitalName);
        txtHospitalName.setBounds(327, 636, 191, 22);
        add(txtEmail);
        txtEmail.setBounds(327, 257, 350, 22);
        add(txtHospitalLocation);
        txtHospitalLocation.setBounds(327, 676, 191, 22);
        add(txtPhone);
        txtPhone.setBounds(327, 393, 350, 22);
        add(txtPassword);
        txtPassword.setBounds(327, 297, 350, 22);

        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "** Select your Gender **", "Male", "Female", "Others", "Do not wish to disclose" }));
        cbGender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(cbGender);
        cbGender.setBounds(327, 337, 159, 22);

        lblRole.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRole.setText("Role :");
        add(lblRole);
        lblRole.setBounds(233, 448, 75, 16);

        cbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "** Choose your Role **", "Doctor", "Patient" }));
        cbRole.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRoleActionPerformed(evt);
            }
        });
        add(cbRole);
        cbRole.setBounds(359, 445, 153, 22);

        btnSignUP.setText("Create Account");
        btnSignUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUPActionPerformed(evt);
            }
        });
        add(btnSignUP);
        btnSignUP.setBounds(423, 791, 112, 23);

        lblDAge.setText("Age :");
        add(lblDAge);
        lblDAge.setBounds(268, 512, 27, 16);

        lblSpeciality.setText("Speciality :");
        add(lblSpeciality);
        lblSpeciality.setBounds(240, 559, 56, 16);

        lblExperience.setText("Experience :");
        add(lblExperience);
        lblExperience.setBounds(234, 599, 63, 16);

        lblHeading1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        lblHeading1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading1.setText("Boston Hospital");
        add(lblHeading1);
        lblHeading1.setBounds(260, 46, 685, 62);

        lblHeading2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblHeading2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeading2.setText("Please Create your New Account..!!");
        add(lblHeading2);
        lblHeading2.setBounds(428, 139, 363, 29);

        lblName.setText("Name :");
        add(lblName);
        lblName.setBounds(215, 223, 38, 16);

        lblEmail.setText("Email :");
        add(lblEmail);
        lblEmail.setBounds(215, 259, 35, 16);

        lblPassword.setText("Password :");
        add(lblPassword);
        lblPassword.setBounds(215, 298, 56, 16);

        lblGender.setText("Gender : ");
        add(lblGender);
        lblGender.setBounds(215, 332, 47, 16);

        lblPhone.setText("Contact Number :");
        add(lblPhone);
        lblPhone.setBounds(215, 369, 95, 16);
        add(txtName);
        txtName.setBounds(327, 223, 350, 22);
        add(txtDAge);
        txtDAge.setBounds(327, 509, 112, 22);
        add(txtSpeciality);
        txtSpeciality.setBounds(327, 556, 112, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\adity\\Downloads\\Signup_1410x1130.png")); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1410, 1130);
    }// </editor-fold>//GEN-END:initComponents

     /*Method to hide the attribute fiels*/
    public void Test(){
        /* Doctor Attributes*/
        lblDAge.setVisible(false);
        lblSpeciality.setVisible(false);
        lblExperience.setVisible(false);
        lblHospitalName.setVisible(false);
        lblHospitalLocation.setVisible(false);
        txtDAge.setVisible(false);
        txtSpeciality.setVisible(false);
        txtExperience.setVisible(false); 
        txtHospitalName.setVisible(false);
        txtHospitalLocation.setVisible(false);
    /*Patient Attributes */
        lblPAge.setVisible(false);
        lblHeight.setVisible(false);
        lblWeight.setVisible(false);
        txtPAge.setVisible(false);
        txtHeight.setVisible(false);
        txtWeight.setVisible(false);
    }
    
    private void cbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRoleActionPerformed
        // TODO add your handling code here:

        if(cbRole.getSelectedItem()=="Doctor"){
            Test();
            lblDAge.setVisible(true);
            lblSpeciality.setVisible(true);
            lblExperience.setVisible(true);
            lblHospitalName.setVisible(true);
            lblHospitalLocation.setVisible(true);
            txtDAge.setVisible(true);
            txtSpeciality.setVisible(true);
            txtExperience.setVisible(true);
            txtHospitalName.setVisible(true);
            txtHospitalLocation.setVisible(true);
        }
        else if(cbRole.getSelectedItem()=="Patient"){
            Test();
            lblPAge.setVisible(true);
            lblHeight.setVisible(true);
            lblWeight.setVisible(true);
            txtPAge.setVisible(true);
            txtHeight.setVisible(true);
            txtWeight.setVisible(true);
        }
        else Test();
    }//GEN-LAST:event_cbRoleActionPerformed

    String name;
    String email;
    String password;
    String gender;
    long phone;
    String role;
    int pAge;
    double height;
    double weight;
    int dAge;
    String speciality;
    double experience;
    String hospitalName;
    String hospitalLocation;
    
    private void btnSignUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUPActionPerformed
        // TODO add your handling code here:
        try{
            name=txtName.getText();
            email=txtEmail.getText();
            password=txtPassword.getText();
            gender=cbGender.getActionCommand();
            phone=Long.parseLong(txtPhone.getText());
            if(cbRole.getSelectedItem()=="Patient"){
                pAge=Integer.parseInt(txtPAge.getText());
                height=Double.parseDouble(txtHeight.getText());
                weight=Double.parseDouble(txtWeight.getText());

                if(checkfield()){
                    if(!(patientHistory.uniqueEmail(email))){
                        Patient p= patientHistory.addPatient();
                        p.setName(name);
                        p.setEmail(email);
                        p.setPassword(password);
                        p.setPhone(phone);
                        p.setRole(role);
                        p.setpAge(pAge);
                        p.setHeight(height);
                        p.setWeight(weight);

                        JOptionPane.showMessageDialog(this, "New Patient Created..!!");

                        txtName.setText("");
                        txtEmail.setText("");
                        txtPassword.setText("");
                        cbGender.setSelectedItem("** Select your Gender **");
                        txtPhone.setText(null);
                        cbRole.setSelectedItem("** Choose your Role **");
                        txtPAge.setText(null);
                        txtHeight.setText(null);
                        txtWeight.setText(null);
                    }
                    else JOptionPane.showMessageDialog(this, "Email ID already exists..!!");
                }
            }
            else{
                dAge=Integer.parseInt(txtDAge.getText());
                speciality=txtSpeciality.getText();
                experience=Double.parseDouble(txtExperience.getText());
                hospitalName=txtHospitalName.getText();
                hospitalLocation=txtHospitalLocation.getText();

                if(checkfield()){
                    if(!(doctorDirectory.uniqueEmail(email))){
                        Doctor d =doctorDirectory.addDoctor();
                        d.setName(name);
                        d.setEmail(email);
                        d.setPassword(password);
                        d.setPhone(phone);
                        d.setRole(role);
                        d.setdAge(dAge);
                        d.setSpeciality(speciality);
                        d.setExperience(experience);
                        d.setHospitalName(hospitalName);
                        d.setHospitalLocation(hospitalLocation);

                        JOptionPane.showMessageDialog(this, "New Doctor Added..!!");

                        txtName.setText("");
                        txtEmail.setText("");
                        txtPassword.setText("");
                        cbGender.setSelectedItem("** Select your Gender **");
                        txtPhone.setText(null);
                        cbRole.setSelectedItem("** Choose your Role **");
                        txtDAge.setText(null);
                        txtSpeciality.setText("");
                        txtExperience.setText(null);
                        txtHospitalName.setText("");
                        txtHospitalLocation.setText("");
                    }
                    else JOptionPane.showMessageDialog(this, "Email ID already exists..!!");
                }
            }
        }
        catch(Exception e){JOptionPane.showMessageDialog(this, "Please enter correct values..!!");}

    }//GEN-LAST:event_btnSignUPActionPerformed

    private boolean checkfield(){
    ArrayList msg=null;
    msg= new ArrayList();
    
     if(name.isBlank()|| !(name.matches("^[a-zA-Z ]*$")))
        {msg.add("Please enter the name without digits or special characters but do not leave it blank");}
     if(email.isBlank()||!(email.matches("^[A-Za-z0-9+_.-]+@(.+)$")))
        msg.add(("Please enter the correct email (xxx@xx.com)"));
     if(password.isBlank())
        msg.add("Password field is empty");
     if(gender.equals("** Select your Gender **"))
         {msg.add("Please Select the Gender");}
     if(!(String.valueOf(phone).matches("^[0-9]{10}$")))
       {msg.add("Please enter the 10 digit mobile number");}
     if(cbRole.getSelectedItem()=="Patient"){
        if(pAge<1||pAge>=100)
        {msg.add("Please enter the correct age between 1 and 100");}
        if(height<30.48 || height>300)
        {msg.add("Please Enter your appropriate height");}
        if(weight<4.4 || weight >500)
         msg.add("Please Enter your Correct weight");
      }
     else if(cbRole.getSelectedItem()=="Doctor"){
         if(dAge<1 || dAge>100)
             msg.add("Please enter the correct age between 1 and 100");
         if(speciality.isBlank()|| !(speciality.matches("^[a-zA-Z ]*$")))
             msg.add("Please enter the Speciality without digits or special characters but do not leave it blank");
         if(experience<0 || experience>75)
             msg.add("Please enter your correct experience");
         if(hospitalName.isBlank()|| !(hospitalName.matches("^[a-zA-Z ]*$")))
             msg.add("Please enter the Hospital name without special characters but do not leave it blank");
         if(hospitalLocation.isBlank()|| !(hospitalLocation.matches("^[a-zA-Z ]*$")))
             msg.add("Please enter the correct location without special characters but do not leave it blank");
     }
     else{msg.add("Please choose a role");}
     
     if(!(msg.isEmpty()))
        {JOptionPane.showMessageDialog(this, msg.toArray());
        msg.clear();
        return false;}
        else 
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignUP;
    private javax.swing.JComboBox<String> cbGender;
    private javax.swing.JComboBox<String> cbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDAge;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblExperience;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHeading1;
    private javax.swing.JLabel lblHeading2;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblHospitalLocation;
    private javax.swing.JLabel lblHospitalName;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPAge;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblSpeciality;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JTextField txtDAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtExperience;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtHospitalLocation;
    private javax.swing.JTextField txtHospitalName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPAge;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSpeciality;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
